# Generated by Django 5.1.3 on 2025-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_created_at_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Arcadio', 'Arcadio'), ('Arnette', 'Arnette'), ('Brooklyn', 'Brooklyn'), ('Freya', 'Freya'), ('Ray-Ban', 'Ray-Ban')], default='Arcadio', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Carbon Fiber', 'Carbon Fiber')], default='Plastic', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
