# Generated by Django 5.1.3 on 2025-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_product_gender_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Arcadio', 'Arcadio'), ('Arnette', 'Arnette'), ('Brooklyn', 'Brooklyn'), ('Cameo', 'Cameo'), ('Freya', 'Freya'), ('Green Vision', 'Green Vision'), ('Jacques Lamount', 'Jacques Lamount'), ('Knockaround', 'Knockaround'), ('Lazer', 'Lazer'), ('LK Bennet', 'LK Bennet'), ('Matrix', 'Matrix'), ('Meridian', 'Meridian'), ('Michael Kors', 'Michael Kors'), ('O’neill', 'O’neill'), ('OMG', 'OMG'), ('Penguin', 'Penguin'), ('Quicksilver', 'Quicksilver'), ('Ray-Ban', 'Ray-Ban'), ('Reserve', 'Reserve'), ('Retro', 'Retro'), ('Roxy', 'Roxy'), ('Shadez', 'Shadez'), ('Solano', 'Solano'), ('Stepper', 'Stepper'), ('Superdry', 'Superdry'), ('Universal', 'Universal'), ('Vogue', 'Vogue'), ('Whizkids', 'Whizkids'), ('Zenith', 'Zenith')], default='Ray-Ban', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Carbon Fiber', 'Carbon Fiber'), ('Mesh Band', 'Mesh Band'), ('Metal', 'Metal'), ('Metal Case', 'Metal Case'), ('Plastic', 'Plastic'), ('Steel Band', 'Steel Band'), ('Steel Case', 'Steel Case')], default='Plastic', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
